language: node_js
node_js:
  - "0.11"
  - "0.10"
before_script: 'npm install -g istanbul'
script: 'istanbul cover node_modules/jasmine-node/bin/jasmine-node --captureExceptions spec/'
after_success: 'cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js'