language: node_js
node_js: 0.11

before_script:
 - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
 - sudo apt-get update && sudo apt-get install git
 - git --version
 - git config --global user.name "SiteManager User" && git config --global user.email "site-manager@example.com"
script:
 - npm run server-unit-test-with-coverage
 - npm run client-unit-test
after_success: npm run coveralls
