language: node_js
node_js: 0.11

before_script:
 - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
 - git config user.name --global "SiteManager User" && git config user.email --global "site-manager@example.com"
script:
 - npm run server-unit-test-with-coverage
 - npm run client-unit-test
after_success: npm run coveralls
