language: node_js
node_js:
  - "0.11"
  
env: BROWSERS=firefox E2E_BROWSERS=Firefox

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run update-webdriver
  - npm install -g istanbul

script: 'istanbul cover -x "spec/**" node_modules/jasmine-node/bin/jasmine-node --captureExceptions spec/'
after_success: 'cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js'
